-- 0001_core_tables_down.sql
-- Reverses 0001_core_tables.sql

DROP TABLE IF EXISTS job_health CASCADE;
DROP TABLE IF EXISTS stats_refresh_queue CASCADE;
DROP TABLE IF EXISTS rate_limits CASCADE;
DROP TABLE IF EXISTS answers CASCADE;
DROP TABLE IF EXISTS rounds CASCADE;
DROP TABLE IF EXISTS game_players CASCADE;
DROP TABLE IF EXISTS game_sessions CASCADE;
DROP TABLE IF EXISTS rooms CASCADE;
DROP TABLE IF EXISTS player_stats CASCADE;
DROP TABLE IF EXISTS players CASCADE;

DROP TYPE IF EXISTS room_status CASCADE;
DROP TYPE IF EXISTS age_group CASCADE;
DROP TYPE IF EXISTS help_used CASCADE;
DROP TYPE IF EXISTS round_end_reason CASCADE;
DROP TYPE IF EXISTS round_status CASCADE;
DROP TYPE IF EXISTS game_status CASCADE;
DROP TYPE IF EXISTS category_mode CASCADE;
DROP TYPE IF EXISTS game_mode CASCADE;
